[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    lvgl/lvgl@^8.3.11
    sensirion/Sensirion I2C SCD4x

build_flags =
    -I include
    ; LVGLの設定ファイルをプロジェクトディレクトリから読み込む設定
    -D LV_CONF_INCLUDE_SIMPLE

    ; TFT_eSPIの設定 (User_Setup.hを利用)
    -D USER_SETUP_LOADED=1
    -include include/User_Setup.h

; パーティションスキームの設定 (Minimal SPIFFS: 1.9MB APP / 190KB SPIFFS)
board_build.partitions = min_spiffs.csv
